options:
  merge-default-rules: true

rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - media
        - ie-lte
  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 2
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  shorthand-values: 0
  variable-for-property: 0
