version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_app.sh
      timeout: 300
      runas: root
