[pytest]
xfail_strict=true
testpaths = tests
log_level = 999
env =
    NOTIFY_ENVIRONMENT=test

filterwarnings =
    error:Applying marks directly:pytest.RemovedInPytest4Warning
addopts = -p no:warnings
