import os
import re
import typing
import uuid

from boto3 import resource
from notifications_utils.s3 import s3upload as utils_s3upload
from werkzeug.datastructures import FileStorage

LOGO_TYPES = typing.Literal["email", "letter"]


class LogoClient:
    LOGO_PATHS = {
        "email": "{filename}",
        # Letter preview PDFs are generated by notifications-template-preview using `LetterPreviewTemplate` in
        # notifications-utils. The templates used by that class hard-code this path for the logo to use on
        # the preview. Ideally we'd be able to pass in any path for it to render the logo. We render a preview before
        # saving the letter branding to the DB (ie making it permanent), so it needs to be able to display temporary
        # logos, so the temp logo path needs to be the same as the perm logo path (until we update utils to handle
        # arbitrary paths).
        "letter": "letters/static/images/letter-template/{filename}",
    }

    def __init__(self):
        # Make sure to call `init_app` to configure the client properly.
        self.region = None
        self.bucket_name = None
        self.client = None

    def init_app(self, application):
        self.region = application.config["AWS_REGION"]
        self.bucket_name = application.config["LOGO_UPLOAD_BUCKET_NAME"]
        self.client = resource("s3")

    def _get_object(self, key_):
        return self.client.Object(self.bucket_name, key_)

    def _slugify(self, text: str) -> str:
        text = text.lower()
        text = re.sub(r"\s+", "-", text)
        text = re.sub(r"[^A-Za-z\d\-]", "", text)
        text = re.sub(r"\-{2,}", "-", text)
        text = text.strip("-")
        return text.lower()

    def get_logo_key(
        self,
        logo_file_name: str,
        logo_type: LOGO_TYPES,
        logo_key_extra: typing.Optional[str] = None,
        temporary: bool = False,
    ) -> str:
        """Returns the s3 object key for a logo

        Pass some arbitrary extra context to `logo_key_extra` - this will be normalised and appended to the
        filename.
        """
        if temporary:
            logo_file_name = f"temp-{logo_file_name}"
        else:
            logo_file_name = logo_file_name[5:] if logo_file_name.startswith("temp-") else logo_file_name

        if logo_key_extra:
            _file_name, _file_ext = os.path.splitext(logo_file_name)
            logo_key_extra = self._slugify(logo_key_extra)
            logo_file_name = f"{_file_name}-{logo_key_extra}{_file_ext}"

        return self.LOGO_PATHS[logo_type].format(filename=logo_file_name)

    def save_temporary_logo(self, file_data: FileStorage, logo_type: LOGO_TYPES) -> str:
        """Returns the S3 object key of the uploaded temporary logo.

        args:
            file_data: file-like object
            logo_type: one of: 'email' or 'letter'

        returns:
            S3 object key (excluding bucket name)
        """
        file_extension = os.path.splitext(file_data.filename)[1]
        content_type = file_data.content_type
        unique_id = str(uuid.uuid4())
        logo_file_name = f"{unique_id}{file_extension}"
        temporary_logo_key = self.get_logo_key(logo_file_name=logo_file_name, logo_type=logo_type, temporary=True)
        utils_s3upload(
            filedata=file_data.stream,
            region=self.region,
            bucket_name=self.bucket_name,
            file_location=temporary_logo_key,
            content_type=content_type,
            tags={"delete-after-7-days": True},
        )
        return temporary_logo_key

    def save_permanent_logo(
        self, temporary_logo_key: str, logo_type: LOGO_TYPES, logo_key_extra: typing.Optional[str] = None
    ) -> str:
        """Takes a temporary logo S3 object key and copies it to an immutable, must-never-be-deleted final location.

        args:
            temporary_logo_key: s3 object key to existing temporary logo
            logo_type: one of: 'email' or 'letter'
            logo_key_extra: some extra context to include in the s3 object key/absolute path. will be normalised.

        returns:
            S3 object key (excluding bucket name)
        """
        logo_key = os.path.basename(temporary_logo_key)

        permanent_logo_key = self.get_logo_key(
            logo_file_name=logo_key, logo_type=logo_type, logo_key_extra=logo_key_extra
        )

        # TaggingDirective='REPLACE' here will strip all tags from the S3 object - ie removes the 'delete-after-7-days'
        # tag, so this new version won't get cleaned up by our lifecycle policy.
        self._get_object(permanent_logo_key).copy_from(
            CopySource="{}/{}".format(self.bucket_name, temporary_logo_key), TaggingDirective="REPLACE"
        )

        return permanent_logo_key


logo_client = LogoClient()
