FROM python:3.4-slim

ENV PYTHONUNBUFFERED=1 \
	DEBIAN_FRONTEND=noninteractive \
	NODEJS_VERSION=6.3.1-1nodesource1~jessie1

RUN \
	echo "Install base packages" \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends \
		apt-transport-https \
		make \
		curl \
		git \
		build-essential \
		libxml2-dev \
		libxslt-dev \
		zlib1g-dev \
		zip \
		rlwrap \

	&& echo "Install nodejs" \
	&& cd /tmp \
	&& curl -sSLO https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/nodejs_${NODEJS_VERSION}_amd64.deb \
	&& dpkg -i /tmp/nodejs_${NODEJS_VERSION}_amd64.deb \

	&& echo "Clean up" \
	&& rm -rf /var/lib/apt/lists/* /tmp/*

RUN \
	echo "Install global pip packages" \
	&& pip install \
		virtualenv \
		awscli

WORKDIR /var/project

COPY entrypoint.sh /usr/local/bin/docker-entrypoint

ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
