"""empty message

Revision ID: 70_unique_email
Revises: 60_add_service
Create Date: 2015-12-17 14:46:52.831849

"""

# revision identifiers, used by Alembic.
revision = '70_unique_email'
down_revision = '60_add_service'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_address', table_name='users')
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.create_index('ix_users_email_address', 'users', ['email_address'], unique=False)
    ### end Alembic commands ###
