"""empty message

Revision ID: 90_remove_user_fk_verify_codes
Revises: 80_remove_services
Create Date: 2016-01-19 20:57:41.986177

"""

# revision identifiers, used by Alembic.
revision = '90_remove_user_fk_verify_codes'
down_revision = '80_remove_services'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('verify_codes_user_id_fkey', 'verify_codes', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('verify_codes_user_id_fkey', 'verify_codes', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
